# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'API - POST' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for API - POST
  pod 'Alamofire', '5.9.1'

end
